[theme]
primaryColor = "#1a73e8"
backgroundColor = "#1c1c1c"
secondaryBackgroundColor = "#2a2a2a"
textColor = "#ffffff"
font = "Helvetica, Arial, sans-serif"

[server]
headless = true
enableCORS = false
