[theme]
primaryColor = "#e82127"  # Tesla Red (for buttons and accents)
backgroundColor = "#0d0d0d"  # Deep black background
secondaryBackgroundColor = "#1a1a1a"  # Slight contrast for sidebars/cards
textColor = "#f2f2f2"  # Soft white for readability
font = "monospace"  # Sleek, techy feel

[server]
enableCORS = false
enableXsrfProtection = false

