[theme]
primaryColor = "#00FFF7"                   # Neon teal accent
backgroundColor = "#0F1117"                # Deep dark background
secondaryBackgroundColor = "#1F222E"       # Slight contrast for cards/sidebar
textColor = "#E0E0E0"                      # Light gray text for readability
font = "sans serif"                        # Required by Streamlit (Orbitron is loaded via CSS)


[server]
enableCORS = false
enableXsrfProtection = false

